# Generated by Django 5.1.3 on 2024-12-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotDialogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=35, verbose_name='Имя пользователя')),
                ('prompt', models.TextField(verbose_name='Вопрос к ассистенту')),
                ('response', models.TextField(verbose_name='Ответ от ассистента')),
                ('created', models.DateField(auto_now=True, verbose_name='Дата сообщения')),
            ],
            options={
                'verbose_name': 'Запись диалога с ботом',
                'verbose_name_plural': 'Записи диалогов с ботом',
            },
        ),
        migrations.CreateModel(
            name='TelegramUserContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='Идентификатор в телеграм')),
                ('first_name', models.CharField(max_length=35, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=35, verbose_name='Фамилия')),
                ('created', models.DateField(auto_now=True, verbose_name='Дата создания')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Контакт из Телеграмм',
                'verbose_name_plural': 'Контакты из Телеграмм',
            },
        ),
        migrations.CreateModel(
            name='UserContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=77, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('created', models.DateField(auto_now=True, verbose_name='Дата создания')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('contact', models.TextField(default='#', max_length=255, verbose_name='Контакт')),
            ],
            options={
                'verbose_name': 'Контакт с формы на сайте',
                'verbose_name_plural': 'Контакты с формы на сайте',
            },
        ),
    ]
